language: python
python:
  - "2.7_with_system_site_packages"
  - "3.2_with_system_site_packages"

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: 
  - sudo apt-get install python-numpy python-scipy
  - pip install neo
  - pip install git+git://github.com/NeuralEnsemble/libNeuroML.git
  - pip install git+git://github.com/rgerkin/pyNeuroML.git
  - pip install git+git://github.com/rgerkin/sciunit.git

# Setting up pre-requirements
before_script:
  - echo $PYTHONPATH
  - ls

# command to run tests, e.g. python setup.py test
script: python example.py
